### ISSUE TITLE
Several notes regarding the code

### ISSUE THREAD

**Issue by Migel1** [nicolas-van/win-cmd-escaper#1]
> raise ValueError("ASCII control codes are not supported")

Tabs are certainly supported.

> elif is_script and c == "%":

Percents are sometimes interpeted by cmd.exe even if used in command line.

For example, the "cmd /c echo %AAA%" command will display the "%AAA%" string as is, but "cmd /c echo %PATH%" will display the contents of the PATH variable, and, moreover, the commands "cmd /c echo %%PATH%%" and "cmd /c echo %AAA%PATH%AAA%" will do this too.
As a workaround you can use the "cmd /c echo %"PATH"%" syntax, in this case third party software will just strip the quotes.
But the workaround will work only until the '"PATH"' variable (name with quotes - such variables can be created in environment too) is defined.

This can be avoided by predefining the QUOTE variable with the "%" value before running the command - "cmd /c echo %QUOTE%PATH%QUOTE%", but this approach can lead to other problems.

**Comment by nicolas-van** [comment]
Yes, sorry but this contribution is completely unusable as it is.

As explained in the [Contributing to this project](https://github.com/nicolas-van/win-cmd-escaper?tab=readme-ov-file#contributing-to-this-project) part of the readme, this project has zero tolerance regarding opinions, speaches, or whatever. This means that only **proven facts** are accepted.

That doesn't mean your contribution can't be useful, it only means that you're doing it the wrong way.

If you think that tabs could be supported in some modes with the current code the solution is simple: alter the code to allow usage of tabs, add tests using tabs in all supported modes, run these tests and propose your updated implementation + tests through a pull request.

If you think the actual implementation regarding the % character handling is bugged, the solution is even simpler: find a case where the implementation does not work, add a test with that case (it will make the test fail, if it doesn't it means you're wrong) then propose that test using a pull request.
